server:
  PROJECT_NAME: "Ticket Api"
  SERVICE_NAME: "ticket_service"
  APP_ENV: "dev"
  API_VER: "v1"
  APP_DEBUG: true
  APP_PROXY: false
  APP_PROXY_HOST: ""
  HTTP_PORT: 8080
  GRPC_PORT: 8080
  TIMEOUT: 15
  APP_SECRET: "very-secret-key"
  JWT_TOKEN_EXPIRE_TIME: 8760
  APP_VERSION: 1.0.0
  READ_TIMEOUT: 5
  WRITE_TIMEOUT: 5
  MAX_CONN_IDLE: 5
  MAX_CONN_AGE: 5

swagger:
  SWAGGER_BASIC_AUTH_USERNAME:
  SWAGGER_BASIC_AUTH_PASSWORD:

cloud:
  GCP_PROJECT_IDENTIFIER:
  AWS_PROJECT_IDENTIFIER:
  GCP_SERVICE_ACCOUNT:

http:
  PORT: 8080
  PPROF_PORT: 8080
  TIMEOUT: 15
  READ_TIMEOUT: 5
  WRITE_TIMEOUT: 5
  COOKIE_LIFE_TIME: 44640
  SESSION_COOKIE_NAME: "session_token"
  SSL_CERT_PATH: ""
  SSL_CERT_KEY: ""

logger:
  DISABLE_CALLER: false
  DISABLE_STACKTRACE: false
  ENCODING: json
  LEVEL: info

postgresql:
  HOST: "db"
  PORT: 5432
  USER: "postgres"
  PASS: "123456"
  DEFAULT_DB: "dev"
  MAX_CONN: 10
  DRIVER: "pgx"
