
--region tickets
CREATE TABLE tickets
(
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(75) NOT NULL,
    description VARCHAR(255) NOT NULL,
    allocation INT8 NOT NULL CHECK(allocation>= 0) DEFAULT 0
);
COMMENT ON TABLE tickets IS 'Tickets';
CREATE INDEX ON tickets USING btree (name);
CREATE INDEX ON tickets USING btree (name, description);

--endregion

--region purchase_logs
CREATE TABLE purchase_logs
(
    log_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INT8 NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    quantity INT8 NOT NULL DEFAULT 0
);
COMMENT ON TABLE purchase_logs IS 'Purchase Logs';
CREATE INDEX ON purchase_logs USING btree (ticket_id);

--endregion